<template>
  <!-- for learnable -->
  <span ref="mathJaxEl" class="latex-mathjax--span"></span>
</template>
<script>
let words = [
  '!',
  '"',
  '$',
  '&',
  "'",
  '(',
  ')',
  '*',
  '+',
  ',',
  '-',
  '.',
  '/',
  '0',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  ':',
  ';',
  '<',
  '</s>',
  '<s>',
  '<unk>',
  '=',
  '>',
  '?',
  '@',
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z',
  '[',
  '\\#',
  '\\$',
  '\\%',
  '\\&',
  '\\(',
  '\\)',
  '\\Alpha',
  '\\Beta',
  '\\Chi',
  '\\Delta',
  '\\Downarrow',
  '\\Epsilon',
  '\\Eta',
  '\\Gamma',
  '\\Iota',
  '\\Kappa',
  '\\Lambda',
  '\\Leftarrow',
  '\\Leftrightarrow',
  '\\Mu',
  '\\NEarrow',
  '\\NWarrow',
  '\\Nu',
  '\\Omega',
  '\\Omicron',
  '\\Phi',
  '\\Pi',
  '\\Psi',
  '\\Re',
  '\\Rho',
  '\\Rightarrow',
  '\\RomanNumeralCaps',
  '\\SEarrow',
  '\\SWarrow',
  '\\Sigma',
  '\\Tau',
  '\\Theta',
  '\\Uparrow',
  '\\Updownarrow',
  '\\Upsilon',
  '\\Xi',
  '\\Zeta',
  '\\[',
  '\\\\',
  '\\]',
  '\\_',
  '\\alpha',
  '\\angle',
  '\\acute',
  '\\approx',
  '\\arccos',
  '\\arccot',
  '\\arccsc',
  '\\arcsec',
  '\\arcsin',
  '\\arctan',
  '\\bar',
  '\\because',
  '\\begin',
  '\\beta',
  '\\binom',
  '\\blackdiamond',
  '\\blackheart',
  '\\blackrectangle',
  '\\blacksquare',
  '\\blackstar',
  '\\blacktriangle',
  '\\blacktriangledown',
  '\\bot',
  '\\bullet',
  '\\cap',
  '\\cdot',
  '\\cdots',
  '\\chi',
  '\\circ',
  '\\clubsuit',
  '\\cmark',
  '\\complement',
  '\\cong',
  '\\cos',
  '\\cot',
  '\\csc',
  '\\cup',
  '\\ddot',
  '\\ddots',
  '\\deletion',
  '\\delta',
  '\\diamond',
  '\\div',
  '\\dot',
  '\\downarrow',
  '\\emptyset',
  '\\end',
  '\\epsilon',
  '\\equiv',
  '\\eta',
  '\\exists',
  '\\female',
  '\\forall',
  '\\frac',
  '\\gamma',
  '\\geq',
  '\\grave',
  '\\hat',
  '\\heart',
  '\\hookleftarrow',
  '\\iiiint',
  '\\iiint',
  '\\iint',
  '\\in',
  '\\infty',
  '\\insert',
  '\\int',
  '\\iota',
  '\\kappa',
  '\\lambda',
  '\\land',
  '\\left',
  '\\leftarrow',
  '\\leftrightarrow',
  '\\leq',
  '\\lg',
  '\\lim',
  '\\ln',
  '\\lnot',
  '\\lor',
  '\\max',
  '\\male',
  '\\mid',
  '\\min',
  '\\mix',
  '\\mp',
  '\\mu',
  '\\napprox',
  '\\nearrow',
  '\\neq',
  '\\nequiv',
  '\\ngeq',
  '\\ni',
  '\\nleq',
  '\\notin',
  '\\notni',
  '\\nparallel',
  '\\nsubset',
  '\\nsupset',
  '\\nsubseteq',
  '\\nsupseteq',
  '\\nu',
  '\\nwarrow',
  '\\odot',
  '\\oiiint',
  '\\oiint',
  '\\oint',
  '\\omega',
  '\\omicron',
  '\\ominus',
  '\\omitted',
  '\\oplus',
  '\\otimes',
  '\\parallel',
  '\\parallelequal',
  '\\parallelogram',
  '\\partial',
  '\\perp',
  '\\phi',
  '\\pi',
  '\\pm',
  '\\pmod',
  '\\prime',
  '\\prod',
  '\\propto',
  '\\psi',
  '\\rectangle',
  '\\rho',
  '\\right',
  '\\rightarrow',
  '\\romannumeral',
  '\\searrow',
  '\\sec',
  '\\sigma',
  '\\sigma',
  '\\sim',
  '\\sin',
  '\\smiley',
  '\\spadesuit',
  '\\sqrt',
  '\\square',
  '\\star',
  '\\subset',
  '\\subseteq',
  '\\subsetneq',
  '\\sum',
  '\\supset',
  '\\supseteq',
  '\\supsetneq',
  '\\swarrow',
  '\\tab',
  '\\tan',
  '\\tau',
  '\\textcircled',
  '\\textperthousand',
  '\\textreferencemark',
  '\\textregistered',
  '\\textsection',
  '\\texttrademark',
  '\\therefore',
  '\\theta',
  '\\tilde',
  '\\times',
  '\\top',
  '\\triangle',
  '\\triangledown',
  '\\uparrow',
  '\\updownarrow',
  '\\upsilon',
  '\\vdots',
  '\\vec',
  '\\wideparen',
  '\\xi',
  '\\xmark',
  '\\zeta',
  '\\{',
  '\\}',
  ']',
  '^',
  '_',
  'a',
  'b',
  'c',
  'd',
  'e',
  'f',
  'g',
  'h',
  'i',
  'j',
  'k',
  'l',
  'm',
  'n',
  'o',
  'p',
  'q',
  'r',
  's',
  't',
  'u',
  'v',
  'w',
  'x',
  'y',
  'z',
  '{',
  '}',
  '、',
  '。',
  '《',
  '》',
  '【',
  '】',
  '￥',
  '￠',
  '£'
]

let transformer = function (value) {
  var str = value;
  for (var i in words) {
    if (value.indexOf(words[i]) !== -1 && words[i].indexOf('\\') !== -1) {
      str = str.split(words[i]).join(words[i] + ' ');
    }
  }
  str = str.split('<unk>').join('');

  str = str.split('\\left arrow').join('\\leftarrow' + ' ');
  str = str.split('\\left rightarrow').join('\\leftrightarrow' + ' ');
  str = str.split('\\right arrow').join('\\rightarrow' + ' ');
  str = str.split('\\nsubset eq').join('\\nsubseteq' + ' ');
  str = str.split('\\nsupset eq').join('\\nsupseteq' + ' ');
  str = str.split('\\subset eq').join('\\subseteq' + ' ');
  str = str.split('\\subset neq').join('\\subsetneq' + ' ');
  str = str.split('\\triangle down').join('\\triangledown' + ' ');
  return str
}

export default {
  name: 'LatexMathjax', // string
  props: {
    content: {
      type: String,
      required: false,
      default: function () {
        return ''
      }
    }
  }, // propsData
  data() {
    return {

      regex: '/\\&/g'
    }
  },
  computed: {
    comContent() {
      return transformer(this.content.replace(this.regex, '&').replace(/\\textcircled/g, '\\enclose{circle}'))
    }
  }, // { [key: string]: Function | { get: Function, set: Function } }
  watch: {
    comContent: {
      handler: function (newValue, oldValue) {
        this.$nextTick(() => {
          this.$refs.mathJaxEl.textContent = ` $$${this.comContent}$$`
          MathJax.typesetPromise([this.$refs.mathJaxEl])
        })
      },
      immediate: true
    }
  }, // { [key: string]: string | Function | Object | Array }
  methods: {}// { [key: string]: Function }
}
</script>
<style lang="scss" scoped>
</style>
